---
title: 'R assignment: Football Appearance Dataset'
author: "Group 2"
date: "2024-06-15"
output:
  pdf_document:
    latex_engine: xelatex
    includes:
      in_header: header.tex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Assignment}
library(tidyverse)
library(DescTools)
library(ggplot2)

my_data <- read_csv("Football_dataset.csv")

#Print the structure of your dataset
str(my_data)

#List the variables in your dataset
variable_list <- names(my_data)
print(variable_list)

#Print the top 15 rows of your dataset
rows_top15 <- head(my_data, n=15)
print(rows_top15)

#Write a user defined function using any of the variables from the data set.
calculate_contribution_points <- function(yellow_cards, red_cards, goals, assists)
  {
    points <- (goals * 3) + (assists * 2) - (yellow_cards * 1) - (red_cards * 3)
    return(points)
  }
# Fetching and storing Frist row values of the dataset
yellow_cards <- my_data[1, "yellow_cards"]
red_cards <- my_data[1, "red_cards"]
goals <- my_data[1, "goals"]
assists <- my_data[1, "assists"]
# Call to function to calculate total points of First row values
total_points <- calculate_contribution_points(yellow_cards, red_cards, goals, assists)
print(paste("Total contribution points for the first player:", total_points))

#Use data manipulation techniques and filter rows based on any logical criteria that exist in your dataset.
player_name_df <- data.frame(my_data$player_name)

players_with_red_cards <- player_name_df %>% filter(my_data$red_cards >= 1)
players_with_red_cards <- unique(players_with_red_cards)
print(paste("Players with red cards are: ",players_with_red_cards))
print(paste("Total number of players with red cards: ", nrow(players_with_red_cards)))

#Identify the dependent & independent variables and use reshaping techniques and create a new data frame by joining those variables from your dataset.
appearance_id<-my_data$appearance_id
player_id<-my_data$player_id
player_name<-my_data$player_name
player_club_id<-my_data$player_club_id
game_id<-my_data$game_id
competition_id<-my_data$competition_id

player_df <- data.frame(appearance_id,player_id,player_name,player_club_id)
game_df <- data.frame(appearance_id,game_id,competition_id)

merged_df <- merge(player_df,game_df,by="appearance_id")
head(merged_df)

#Remove missing values in your dataset.
my_data <- my_data %>% filter(!is.na(my_data$appearance_id),!is.na(my_data$game_id),!is.na(my_data$player_id),!is.na(my_data$player_club_id),!is.na(my_data$player_current_club_id),!is.na(my_data$date),!is.na(my_data$player_name),!is.na(my_data$competition_id),!is.na(my_data$yellow_cards),!is.na(my_data$red_cards),!is.na(my_data$goals),!is.na(my_data$assists),!is.na(my_data$minutes_played))
head(my_data)

#Identify and remove duplicated data in your dataset
my_data <- my_data %>% distinct()
head(my_data)

#Reorder multiple rows in descending order
my_data <- my_data %>% arrange(desc(player_id),desc(goals))
head(my_data)

#Rename some of the column names in your dataset
my_data_updated<- my_data %>% rename(player_full_name=player_name, goals_scored=goals, minutes=minutes_played)
print(paste("Column names after update:"))
print(colnames(my_data_updated))

#Add new variables in your data frame by using a mathematical function 
my_data<- my_data%>% mutate(contribution_points = goals + assists + 0.5 * yellow_cards - red_cards)
head(my_data$contribution_points)

#Create a training set using random number generator engine.
set.seed(123)
train_indices <- sample(1:nrow(my_data), 0.7 * nrow(my_data))
train_data <- my_data[train_indices, ]
head(train_data)

#Print the summary statistics of your dataset
summary(my_data)

#Use any of the numerical variables from the dataset and perform the following statistical functions: Mean, Median, Mode, Range
mean_value<- mean(my_data$minutes_played)
print(paste("Mean value: ",mean_value))

median_value<-median(my_data$minutes_played)
print(paste("Median value: ",median_value))

mode_value <- Mode(my_data$minutes_played)
print(paste("Mode value: ",mode_value))

range_value<-range(my_data$minutes_played)
print(paste("Range value: ",range_value))


#Plot a scatter plot for any 2 variables in your dataset

my_data_subset <- my_data[1:2000, ]
my_data_subset$date <- as.Date(my_data_subset$date, format = "%d-%m-%Y")
ggplot(my_data_subset, aes(x = date, y = minutes_played, color = goals)) + geom_point(color = "steelblue", size = 0.5) +
labs(title = "Minutes Played Over Time",x = "Date",y = "Minutes Played",color="Goals") +
theme(axis.text.x = element_text(angle = 60, hjust = 1)) 

#Plot a bar plot for any 2 variables in your dataset
new_my_data <- my_data %>% group_by(competition_id) %>% summarise(max_goals = max(goals))

ggplot(new_my_data, aes(x = as.factor(competition_id), y = max_goals)) +
geom_bar(stat = "identity", fill = "seagreen4", width = 0.2) +
labs(title = "Maximum Goals scored in various Competitions",x = "Competitions",y = "Maximum Goals") +
theme(axis.text.x =element_text(angle=60, hjust=1))


#Find the correlation between any 2 variables by applying Pearson correlation
correlation <- cor(my_data$yellow_cards, my_data$minutes_played, method = "pearson")
print(correlation)

```
